import './globals.css';
import Navbar from '../components/Navbar/index';
import Footer from '../components/Footer/Footer';
import Provider from './api/context/ClientProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';


export const metadata = {
  title: 'Sikho - Personalized Professional Learning',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
